server:
    port: 8100

spring:
    datasource:
        url: jdbc:mysql://springstudy.cgllngfx5zdm.ap-northeast-2.rds.amazonaws.com:3306/Ringleader
        username: admin
        password: dla23689!!
        driver-class-name: com.mysql.cj.jdbc.Driver # mysql
