server:
    port: 9100


spring:
#    application:
#        name:ringleader
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: ENC(kf9NqZpVN2tVqU1KSX1a0g9Dv3qUF9nyMmuZvReEttfLkJaxJcosxmWqKFwvKZrdNyYCMU1VHHjsO4B0BysfT3ANxHfN9SrsMTBbA1XaApUhY9wbm2cTPrORxAlBd78C)
        username: ENC(Mx+2Ctb2LvBpTmKimKiEOA==)
        password: ENC(XBxvB3vT19jsMR5UY88SoAvzt/wLoeAc)

jasypt:
    encryptor:
        bean: jasyptStringEncryptor
